service: aws-nodejs
AWSTemplateFormatVersion : '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
    LambdaFunction:
      Type: AWS::Serverless::Function
      Properties:
        Handler: index.handler
        Environment:
          Variables:
            QUEUE_URL:
            ACCESS_KEY:
            SECRET_KEY:
        Runtime: nodejs8.10
        Events: 
          KetchupApi:
            Type: Api
            Properties:
              Path: /
              Method: GET